const interests = [
  "Equestrian",
  "Korean Food",
  "Inline Skate",
  "Live Music",
  "Musical Instrument",
  "Investment",
  "Jetski",
  "Literature",
  "Jogging",
  "Marathon",
  "Mental Health Awareness",
  "Pig Roast",
  "Motorbike Racing",
  "Clubbing",
  "Killing Time",
  "Musical Writing",
  "Metaverse",
  "Trap Music",
  "Military",
  "MLB",
  "Mindfulness",
  "Trying New Things",
  "Olympic Gymnastics",
  "Online Games",
  "Paragliding",
  "Online Broker",
  "Nightlife",
  "Online Shopping",
  "NBA",
  "Pole Dancing",
  "Pub Quiz",
  "Nintendo",
  "PlayStation",
  "Pimms",
  "Pinterest",
  "Rave",
  "Pentathlon",
  "Saxophonist",
  "Pho",
  "Self Development",
  "Potterhead",
  "Pride",
  "Social Development",
  "Rock Climbing",
  "Sauna",
  "Rock",
  "Sci-Fi",
  "Samba",
  "Sake",
  "Pubs",
  "Roblox",
  "SoundCloud",
  "Tango",
  "Shisha",
  "Spotify",
  "Town Festivities"
];

export default interests;