LANGUAGE_CODES = [
    ('af', 'Afrikaans'),
    ('sq', 'Albanian'),
    ('am', 'Amharic'),
    ('ar', 'Arabic'),
    ('hy', 'Armenian'),
    ('as', 'Assamese'),
    ('az', 'Azerbaijani (Latin)'),
    ('bn', 'Bangla'),
    ('ba', 'Bashkir'),
    ('eu', 'Basque'),
    ('bho', 'Bhojpuri'),
    ('brx', 'Bodo'),
    ('bs', 'Bosnian (Latin)'),
    ('bg', 'Bulgarian'),
    ('yue', 'Cantonese (Traditional)'),
    ('ca', 'Catalan'),
    ('lzh', 'Chinese (Literary)'),
    ('zh-Hans', 'Chinese Simplified'),
    ('zh-Hant', 'Chinese Traditional'),
    ('sn', 'chiShona'),
    ('hr', 'Croatian'),
    ('cs', 'Czech'),
    ('da', 'Danish'),
    ('prs', 'Dari'),
    ('dv', 'Divehi'),
    ('doi', 'Dogri'),
    ('nl', 'Dutch'),
    ('en', 'English'),
    ('et', 'Estonian'),
    ('fo', 'Faroese'),
    ('fj', 'Fijian'),
    ('fil', 'Filipino'),
    ('fi', 'Finnish'),
    ('fr', 'French'),
    ('fr-ca', 'French (Canada)'),
    ('gl', 'Galician'),
    ('ka', 'Georgian'),
    ('de', 'German'),
    ('el', 'Greek'),
    ('gu', 'Gujarati'),
    ('ht', 'Haitian Creole'),
    ('ha', 'Hausa'),
    ('he', 'Hebrew'),
    ('hi', 'Hindi'),
    ('mww', 'Hmong Daw (Latin)'),
    ('hu', 'Hungarian'),
    ('is', 'Icelandic'),
    ('ig', 'Igbo'),
    ('id', 'Indonesian'),
    ('ikt', 'Inuinnaqtun'),
    ('iu', 'Inuktitut'),
    ('iu-Latn', 'Inuktitut (Latin)'),
    ('ga', 'Irish'),
    ('it', 'Italian'),
    ('ja', 'Japanese'),
    ('kn', 'Kannada'),
    ('ks', 'Kashmiri'),
    ('kk', 'Kazakh'),
    ('km', 'Khmer'),
    ('rw', 'Kinyarwanda'),
    ('tlh-Latn', 'Klingon'),
    ('tlh-Piqd', 'Klingon (plqaD)'),
    ('gom', 'Konkani'),
    ('ko', 'Korean'),
    ('ku', 'Kurdish (Central)'),
    ('kmr', 'Kurdish (Northern)'),
    ('ky', 'Kyrgyz (Cyrillic)'),
    ('lo', 'Lao'),
    ('lv', 'Latvian'),
    ('lt', 'Lithuanian'),
    ('ln', 'Lingala'),
    ('dsb', 'Lower Sorbian'),
    ('lug', 'Luganda'),
    ('mk', 'Macedonian'),
    ('mai', 'Maithili'),
    ('mg', 'Malagasy'),
    ('ms', 'Malay (Latin)'),
    ('ml', 'Malayalam'),
    ('mt', 'Maltese'),
    ('mi', 'Maori'),
    ('mr', 'Marathi'),
    ('mn-Cyrl', 'Mongolian (Cyrillic)'),
    ('mn-Mong', 'Mongolian (Traditional)'),
    ('my', 'Myanmar'),
    ('ne', 'Nepali'),
    ('nb', 'Norwegian'),
    ('nya', 'Nyanja'),
    ('or', 'Odia'),
    ('ps', 'Pashto'),
    ('fa', 'Persian'),
    ('pl', 'Polish'),
    ('pt', 'Portuguese (Brazil)'),
    ('pt-pt', 'Portuguese (Portugal)'),
    ('pa', 'Punjabi'),
    ('otq', 'Queretaro Otomi'),
    ('ro', 'Romanian'),
    ('run', 'Rundi'),
    ('ru', 'Russian'),
    ('sm', 'Samoan (Latin)'),
    ('sr-Cyrl', 'Serbian (Cyrillic)'),
    ('sr-Latn', 'Serbian (Latin)'),
    ('st', 'Sesotho'),
    ('nso', 'Sesotho sa Leboa'),
    ('tn', 'Setswana'),
    ('sd', 'Sindhi'),
    ('si', 'Sinhala'),
    ('sk', 'Slovak'),
    ('sl', 'Slovenian'),
    ('so', 'Somali (Arabic)'),
    ('es', 'Spanish'),
    ('sw', 'Swahili (Latin)'),
    ('sv', 'Swedish'),
    ('ty', 'Tahitian'),
    ('ta', 'Tamil'),
    ('tt', 'Tatar (Latin)'),
    ('te', 'Telugu'),
    ('th', 'Thai'),
    ('bo', 'Tibetan'),
    ('ti', 'Tigrinya'),
    ('to', 'Tongan'),
    ('tr', 'Turkish'),
    ('tk', 'Turkmen (Latin)'),
    ('uk', 'Ukrainian'),
    ('hsb', 'Upper Sorbian'),
    ('ur', 'Urdu'),
    ('ug', 'Uyghur (Arabic)'),
    ('uz', 'Uzbek (Latin)'),
    ('vi', 'Vietnamese'),
    ('cy', 'Welsh'),
    ('xh', 'Xhosa'),
    ('yo', 'Yoruba'),
    ('yua', 'Yucatec Maya'),
    ('zu', 'Zulu'),
]

LOCALES_BCP_47= [

    ('af-ZA', 'Afrikaans (South Africa)'),
    ('am-ET', 'Amharic (Ethiopia)'),
    ('ar-AE', 'Arabic (United Arab Emirates)'),
    ('ar-BH', 'Arabic (Bahrain)'),
    ('ar-DZ', 'Arabic (Algeria)'),
    ('ar-EG', 'Arabic (Egypt)'),
    ('ar-IL', 'Arabic (Israel)'),
    ('ar-IQ', 'Arabic (Iraq)'),
    ('ar-JO', 'Arabic (Jordan)'),
    ('ar-KW', 'Arabic (Kuwait)'),
    ('ar-LB', 'Arabic (Lebanon)'),
    ('ar-LY', 'Arabic (Libya)'),
    ('ar-MA', 'Arabic (Morocco)'),
    ('ar-OM', 'Arabic (Oman)'),
    ('ar-PS', 'Arabic (Palestinian Authority)'),
    ('ar-QA', 'Arabic (Qatar)'),
    ('ar-SA', 'Arabic (Saudi Arabia)'),
    ('ar-SY', 'Arabic (Syria)'),
    ('ar-TN', 'Arabic (Tunisia)'),
    ('ar-YE', 'Arabic (Yemen)'),
    ('az-AZ', 'Azerbaijani (Latin, Azerbaijan)'),
    ('bg-BG', 'Bulgarian (Bulgaria)'),
    ('bn-IN', 'Bengali (India)'),
    ('bs-BA', 'Bosnian (Bosnia and Herzegovina)'),
    ('ca-ES', 'Catalan'),
    ('cs-CZ', 'Czech (Czechia)'),
    ('cy-GB', 'Welsh (United Kingdom)'),
    ('da-DK', 'Danish (Denmark)'),
    ('de-AT', 'German (Austria)'),
    ('de-CH', 'German (Switzerland)'),
    ('de-DE', 'German (Germany)'),
    ('el-GR', 'Greek (Greece)'),
    ('en-AU', 'English (Australia)'),
    ('en-CA', 'English (Canada)'),
    ('en-GB', 'English (United Kingdom)'),
    ('en-GH', 'English (Ghana)'),
    ('en-HK', 'English (Hong Kong SAR)'),
    ('en-IE', 'English (Ireland)'),
    ('en-IN', 'English (India)'),
    ('en-KE', 'English (Kenya)'),
    ('en-NG', 'English (Nigeria)'),
    ('en-NZ', 'English (New Zealand)'),
    ('en-PH', 'English (Philippines)'),
    ('en-SG', 'English (Singapore)'),
    ('en-TZ', 'English (Tanzania)'),
    ('en-US', 'English (United States)'),
    ('en-ZA', 'English (South Africa)'),
    ('es-AR', 'Spanish (Argentina)'),
    ('es-BO', 'Spanish (Bolivia)'),
    ('es-CL', 'Spanish (Chile)'),
    ('es-CO', 'Spanish (Colombia)'),
    ('es-CR', 'Spanish (Costa Rica)'),
    ('es-CU', 'Spanish (Cuba)'),
    ('es-DO', 'Spanish (Dominican Republic)'),
    ('es-EC', 'Spanish (Ecuador)'),
    ('es-ES', 'Spanish (Spain)'),
    ('es-GQ', 'Spanish (Equatorial Guinea)'),
    ('es-GT', 'Spanish (Guatemala)'),
    ('es-HN', 'Spanish (Honduras)'),
    ('es-MX', 'Spanish (Mexico)'),
    ('es-NI', 'Spanish (Nicaragua)'),
    ('es-PA', 'Spanish (Panama)'),
    ('es-PE', 'Spanish (Peru)'),
    ('es-PR', 'Spanish (Puerto Rico)'),
    ('es-PY', 'Spanish (Paraguay)'),
    ('es-SV', 'Spanish (El Salvador)'),
    ('es-US', 'Spanish (United States)'),
    ('es-UY', 'Spanish (Uruguay)'),
    ('es-VE', 'Spanish (Venezuela)'),
    ('et-EE', 'Estonian (Estonia)'),
    ('eu-ES', 'Basque'),
    ('fa-IR', 'Persian (Iran)'),
    ('fi-FI', 'Finnish (Finland)'),
    ('fil-PH', 'Filipino (Philippines)'),
    ('fr-BE', 'French (Belgium)'),
    ('fr-CA', 'French (Canada)'),
    ('fr-CH', 'French (Switzerland)'),
    ('fr-FR', 'French (France)'),
    ('ga-IE', 'Irish (Ireland)'),
    ('gl-ES', 'Galician'),
    ('gu-IN', 'Gujarati (India)'),
    ('he-IL', 'Hebrew (Israel)'),
    ('hi-IN', 'Hindi (India)'),
    ('hr-HR', 'Croatian (Croatia)'),
    ('hu-HU', 'Hungarian (Hungary)'),
    ('hy-AM', 'Armenian (Armenia)'),
    ('id-ID', 'Indonesian (Indonesia)'),
    ('is-IS', 'Icelandic (Iceland)'),
    ('it-CH', 'Italian (Switzerland)'),
    ('it-IT', 'Italian (Italy)'),
    ('ja-JP', 'Japanese (Japan)'),
    ('jv-ID', 'Javanese (Latin, Indonesia)'),
    ('ka-GE', 'Georgian (Georgia)'),
    ('kk-KZ', 'Kazakh (Kazakhstan)'),
    ('km-KH', 'Khmer (Cambodia)'),
    ('kn-IN', 'Kannada (India)'),
    ('ko-KR', 'Korean (Korea)'),
    ('lo-LA', 'Lao (Laos)'),
    ('lt-LT', 'Lithuanian (Lithuania)'),
    ('lv-LV', 'Latvian (Latvia)'),
    ('mk-MK', 'Macedonian (North Macedonia)'),
    ('ml-IN', 'Malayalam (India)'),
    ('mn-MN', 'Mongolian (Mongolia)'),
    ('mr-IN', 'Marathi (India)'),
    ('ms-MY', 'Malay (Malaysia)'),
    ('mt-MT', 'Maltese (Malta)'),
    ('my-MM', 'Burmese (Myanmar)'),
    ('nb-NO', 'Norwegian Bokmål (Norway)'),
    ('ne-NP', 'Nepali (Nepal)'),
    ('nl-BE', 'Dutch (Belgium)'),
    ('nl-NL', 'Dutch (Netherlands)'),
    ('pa-IN', 'Punjabi (India)'),
    ('pl-PL', 'Polish (Poland)'),
    ('ps-AF', 'Pashto (Afghanistan)'),
    ('pt-BR', 'Portuguese (Brazil)'),
    ('pt-PT', 'Portuguese (Portugal)'),
    ('ro-RO', 'Romanian (Romania)'),
    ('ru-RU', 'Russian (Russia)'),
    ('si-LK', 'Sinhala (Sri Lanka)'),
    ('sk-SK', 'Slovak (Slovakia)'),
    ('sl-SI', 'Slovenian (Slovenia)'),
    ('so-SO', 'Somali (Somalia)'),
    ('sq-AL', 'Albanian (Albania)'),
    ('sr-RS', 'Serbian (Cyrillic, Serbia)'),
    ('sv-SE', 'Swedish (Sweden)'),
    ('sw-KE', 'Swahili (Kenya)'),
    ('sw-TZ', 'Swahili (Tanzania)'),
    ('ta-IN', 'Tamil (India)'),
    ('te-IN', 'Telugu (India)'),
    ('th-TH', 'Thai (Thailand)'),
    ('tr-TR', 'Turkish (Türkiye)'),
    ('uk-UA', 'Ukrainian (Ukraine)'),
    ('ur-IN', 'Urdu (India)'),
    ('uz-UZ', 'Uzbek (Latin, Uzbekistan)'),
    ('vi-VN', 'Vietnamese (Vietnam)'),
    ('wuu-CN', 'Chinese (Wu, Simplified)'),
    ('yue-CN', 'Chinese (Cantonese, Simplified)'),
    ('zh-CN', 'Chinese (Mandarin, Simplified)'),
    ('zh-CN-shandong', 'Chinese (Jilu Mandarin, Simplified)'),
    ('zh-CN-sichuan', 'Chinese (Southwestern Mandarin, Simplified)'),
    ('zh-HK', 'Chinese (Cantonese, Traditional)'),
    ('zh-TW', 'Chinese (Taiwanese Mandarin, Traditional)'),
    ('zu-ZA', 'Zulu (South Africa)'),
]

SECRET_KEY = "1b9d6bcd-bbfd-4b2d-9b5d-ab8dfbbd4bed"
PASSWORD = "vqbj nzvr yzir wlvi"
USER = "tum1@williams.edu"

