# Generated by Django 5.0.1 on 2024-02-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_is_student_userprofile_is_tutor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('caller_user_id', models.CharField(max_length=100)),
                ('callee_user_id', models.CharField(max_length=100)),
            ],
        ),
    ]
