# Generated by Django 5.0.1 on 2024-02-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_matchrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchrequest',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
